28_Latihan Blog + Name + Namespace/blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.index, name="index"),
	url(r'^post/(?P<slugInput>[\w-]+)/$', views.detailPost, name="detail"),
	url(r'^category/(?P<categoryInput>[\w-]+)/$', views.categoryPost, name="category"),
]

28_Latihan Blog + Name + Namespace/mywebsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

urlpatterns = [
	url(r'^$', views.index, name = "index"),
	url(r'^blog/',include('blog.urls', namespace="blog")),
    url(r'^admin/',admin.site.urls),
]

28_Latihan Blog + Name + Namespace/blog/models.py
from django.db import models
from django.utils.text import slugify

# Create your models here.

class Post(models.Model):
	judul		= models.CharField(max_length=255)
	body		= models.TextField()
	category	= models.CharField(max_length=255)
	publish		= models.DateTimeField(auto_now_add = True)
	update		= models.DateTimeField(auto_now = True)
	slug		= models.SlugField(blank=True, editable = False)


	def save(self):
		self.slug = slugify(self.judul)
		super(Post, self).save()

	def __str__(self):
		return "{}. {}".format(self.id,self.judul)

28_Latihan Blog + Name + Namespace/blog/views.py
from django.shortcuts import render

# Create your views here.

from .models import Post

def index(request):
	posts = Post.objects.all();
	categories = Post.objects.values('category').distinct();
	context = {
		'Judul':'Home Blog',
		'Content':'ini adalah halaman blog',
		'Categories':categories,
		'Posts':posts,
	}

	return render(request,'blog/index.html',context)

def categoryPost(request,categoryInput):
	posts = Post.objects.filter(category=categoryInput);
	categories = Post.objects.values('category').distinct();
	context = {
		'Judul':'Home Blog',
		'Content':'tampilkan berdasarkan category',
		'Categories':categories,
		'Posts':posts,
	}

	return render(request,'blog/category.html',context)


def detailPost(request,slugInput):
	posts = Post.objects.get(slug=slugInput);
	categories = Post.objects.values('category').distinct();
	context = {
		'Judul':'Home Blog',
		'Content':'ini adalah halaman blog',
		'Categories':categories,
		'Posts':posts,
	}

	return render(request,'blog/detail.html',context)

28_Latihan Blog + Name + Namespace/mywebsite/views.py
from django.shortcuts import render


def index(request):
	context = {
		'Judul':'Home Page',
		'Content':'ini adalah home page dari website ini'
	}

	return render(request,'index.html',context)

28_Latihan Blog + Name + Namespace/templates/snippets/navbar.html
<nav class="navbar fixed-top navbar-expand-sm navbar-dark bg-dark">
		<div class="container">
			<a class="navbar-brand" href="#">
				<h1>Kelas Terbuka</h1>
			</a>

			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav ml-auto">
					<li class="nav-item">
						<a class="nav-link" href="{% url "index" %}">
							Home
						</a>
					</li>

					<li class="nav-item">
						<a class="nav-link" href="{% url "blog:index" %}">
							Blog
						</a>
					</li>

					<li class="nav-item">
						<a class="nav-link" href="{% url "admin:index" %}">
							Admin
						</a>
					</li>
				</ul>
			</div>

		</div>
	</nav>

28_Latihan Blog + Name + Namespace/templates/snippets/scripts.html
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

28_Latihan Blog + Name + Namespace/templates/snippets/styles.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">